### PR TITLE
Fix: "ESC" to cancelling the quilt rendering.

### PR DESCRIPTION
**Pull request by regcs**
The next attempt to fix the bug which prevents cancelling the quilt rendering (issue #33). Could you check again, @GottfriedHofmann?

### CODE REVIEW

**Comment by GottfriedHofmann** [comment]
Hmm, still not working. It seems like I can cancels the rendering of one view but that's it, it keeps rendering. Same for animation. Does it work on your end?

**Comment by regcs** [comment]
Yeah, it works fine on my end. That's what is making it hard to fix - kind of flying blind. Hm. A bit out of idea here for now. Maybe you can look into it based on the fix-cancel-render branch?

**Comment by regcs** [comment]
@GottfriedHofmann I just decided to try something else. Could you test the update to the [`fix-cancel-render`](https://github.com/regcs/AliceLG/tree/fix-cancel-render) branch again?

**Comment by GottfriedHofmann** [comment]
I just tested it again and it still keeps rendering, even when I try to hit ESC very quickly...

**Comment by regcs** [comment]
Ok, thanks for testing. I am currently overhauling the render operator - I will try to find a new mechanism to handle the render pipeline, but I am not sure I will find one. Anyway, due to the large changes that are going to come in this operator and the fact that noone else complaint about this issue so far, I decided not to fix this in Alice/LG 1.1 anymore.

Probably, I will integrate a cancel button in addition to trying to fix the "ESC" problem for version 2.0.

**Pull request closed without merging**
