### PR TITLE
Add suffix with metadata to quilt filename that can be read by other …

### PR DESCRIPTION
**Pull request by GottfriedHofmann**
…tools like HoloPlay Studio.

The format of the suffix is: _qs{COLUMNS}x{ROWS}y{QUILTASPECT}
Example filename: quiltname_qs5x9a1.6.png

### CODE REVIEW

**Comment by regcs** [comment]
This commit unfortunately introduces a bug where the views are not deleted automatically anymore, if the user chooses to keep only the view or if they didn't give a filename. So there must be some spots in the code that are missing the "quiltSuffix" addition. (During the refactor I am working on, I will also change the render operator so that simple changes like that can't introduce a bug - at the moment there is too much code redundancy in this operator, which makes it far to risky too overlook something.)

**Suggestion for this change:**
At least I would prefer the version without the suffix, which I can easily add myself by file naming if I need. But I understand, that others would find it handy to have it added automatically. Therefore, I think it would also be good if we introduce an option (maybe in the add-on's preference pane) where one can toggle on/off if a suffix is added or not.

**Review by regcs — CHANGES_REQUESTED** [review]
This commit unfortunately introduces a bug where the views are not deleted automatically anymore, if the user chooses to keep only the view or if they didn't give a filename. So there must be some spots in the code that are missing the "quiltSuffix" addition. (During the refactor I am working on, I will also change the render operator so that simple changes like that can't introduce a bug - at the moment there is too much code redundancy in this operator, which makes it far to risky too overlook something.)

**Suggestion for this feature:**
At least I would prefer the version without the suffix, which I can easily add myself by file naming if I need. But I understand, that others would find it handy to have it added automatically. Therefore, I think it would also be good if we introduce an option (maybe in the add-on's preference pane) where one can toggle on/off if a suffix is added or not.

**Comment by GottfriedHofmann** [comment]
Fixed the non-cleanup bug for both still images and animation sequences, even when no filename is specified. I agree that there a lot of code duplication currently.

I added an option for the user to enable or disable the metadata suffix. I set the default to enabled because I think most users will want to use the addon to create content that is used somewhere else in the Looking Glass ecosystem where having the metadata comes in handy.

**Review by regcs — CHANGES_REQUESTED** [review]
Yeah, definitely. We will deal with the code redundancy during the refactor. 

Unfortunately, there still some minor issues with this pull request:
- the "Add Metadata" must not be disabled if no device is detected. I would recommend to reintroduce row_0 and add another row_1 for the new "render_add_suffix" prop and change the subsequent row number variables. Then you can disable the row_0, but keep the row_1 enabled if needed.
- Unfortunately, when no name is specified the final quilt file is not deleted. However, when no name is specified in Blender then no render result should be written to disk, since this is the behavior for normal rendering as well.
- The commit also seems re-introduces issue #7, which was resolved by 1e06ee9250a416bedbeee0a6ca1c2b566e7dcdf8 some week ago.

**Comment by GottfriedHofmann** [comment]
>     * the "Add Metadata" must not be disabled if no device is detected. I would recommend to reintroduce row_0 and add another row_1 for the new "render_add_suffix" prop and change the subsequent row number variables. Then you can disable the row_0, but keep the row_1 enabled if needed.

I made the fix but named the new row "row_metadata" because I am worried I might introduce additional bugs by handling those numbers. We could name them all like "row_preset", "row_orientation" etc...

>     * Unfortunately, when no name is specified the final quilt file is not deleted. However, when no name is specified in Blender then no render result should be written to disk, since this is the behavior for normal rendering as well.

Fixed.

>     * The commit also re-introduces issue [[Render Animation Quilt] Delete views of finished quilts #7](https://github.com/regcs/AliceLG/issues/7), which was resolved by [1e06ee9](https://github.com/regcs/AliceLG/commit/1e06ee9250a416bedbeee0a6ca1c2b566e7dcdf8) some week ago.

I cannot reproduce this. For me, the views deleted after each frame is rendered. Here is a video:
https://www.dropbox.com/s/2jr2grmpnrrx0l5/aliceLG_quiltsuffix_render_anim_view_cleanup.mp4?dl=0

>     * If the rendering is aborted (ESC), the files are not deleted as expected. Please check the cancel() method of the operator as well.

Unfortunately I cannot test this because aborting the rendering with ESC does not work for me, see the video above. I also tested this on master.

**Comment by regcs** [comment]
> I made the fix but named the new row "row_metadata" because I am worried I might introduce additional bugs by handling those numbers. We could name them all like "row_preset", "row_orientation" etc...

Yes, that's a good idea. I plan to put all UI related code in a separate file "ui.py" during the refactor. Do you want to take care of the variable renaming before or after that?
 
> I cannot reproduce this. For me, the views get deleted after each frame is rendered. Here is a video:
> 
> https://www.dropbox.com/s/2jr2grmpnrrx0l5/aliceLG_quiltsuffix_render_anim_view_cleanup.mp4?dl=0

Hm, strange. I tested it again and you are right. It works. So, either I messed up something during testing yesterday or it only occurs under very specific circumstances. Maybe, I accidentally selected "View and Quilt Files" for the "output". Sorry for the confusion!

> ... aborting the rendering with ESC does not work for me, see the video above. I also tested this on master.

About the "ESC" :  On my Mac it works, although I also recognized now that I sometimes have to hit the key twice. Maybe this is something timing related. I will look into it during the refactor of the rendering operator.

**Comment by GottfriedHofmann** [comment]
> > I made the fix but named the new row "row_metadata" because I am worried I might introduce additional bugs by handling those numbers. We could name them all like "row_preset", "row_orientation" etc...
> 
> Yes, that's a good idea. I plan to put all UI related code in a separate file "ui.py" during the refactor. Do you want to take care of the variable renaming before or after that?

Let's do it right away 🙂

**Comment by regcs** [comment]
Perfect, thanks!

**Pull request merged**
